package e2e_test

import (
	"context"
	"fmt"
	"net/http"
	"testing"

	"github.com/abdelrahman146/kyora/internal/platform/auth"
	"github.com/abdelrahman146/kyora/internal/platform/types/role"
	"github.com/abdelrahman146/kyora/internal/tests/testutils"
	"github.com/shopspring/decimal"
	"github.com/stretchr/testify/suite"
)

type InventoryVariantsSuite struct {
	suite.Suite
	accountHelper   *AccountTestHelper
	inventoryHelper *InventoryTestHelper
}

func (s *InventoryVariantsSuite) SetupSuite() {
	s.accountHelper = NewAccountTestHelper(testEnv.Database, testEnv.CacheAddr, e2eBaseURL)
	s.inventoryHelper = NewInventoryTestHelper(testEnv.Database, e2eBaseURL)
}

func (s *InventoryVariantsSuite) resetDB() {
	s.NoError(testutils.TruncateTables(testEnv.Database, inventoryTables...))
}

func (s *InventoryVariantsSuite) SetupTest() {
	s.resetDB()
}

func (s *InventoryVariantsSuite) TearDownTest() {
	s.resetDB()
}

func (s *InventoryVariantsSuite) TestCreateVariant_Success_SkuAutoGenerated() {
	ctx := context.Background()
	_, ws, token, err := s.accountHelper.CreateTestUser(ctx, "admin@example.com", "Password123!", "Admin", "User", role.RoleAdmin)
	s.NoError(err)
	s.NoError(s.accountHelper.CreateTestSubscription(ctx, ws.ID))
	biz, err := s.inventoryHelper.CreateTestBusiness(ctx, ws.ID, "test-biz")
	s.NoError(err)
	cat, err := s.inventoryHelper.CreateTestCategory(ctx, biz.ID, "Cat", "cat")
	s.NoError(err)
	prod, err := s.inventoryHelper.CreateTestProduct(ctx, biz.ID, cat.ID, "Prod", "")
	s.NoError(err)

	payload := map[string]interface{}{
		"productId":          prod.ID,
		"code":               "RED",
		"sku":                "",
		"costPrice":          "10",
		"salePrice":          "15",
		"stockQuantity":      2,
		"stockQuantityAlert": 5,
	}
	resp, err := s.inventoryHelper.Client.AuthenticatedRequest("POST", "/v1/businesses/test-biz/inventory/variants", payload, token)
	s.NoError(err)
	defer resp.Body.Close()
	s.Equal(http.StatusCreated, resp.StatusCode)

	var result map[string]interface{}
	s.NoError(testutils.DecodeJSON(resp, &result))
	s.NotEmpty(result["id"])
	s.Equal(prod.ID, result["productId"])
	s.Equal("Prod - RED", result["name"])
	s.Equal("RED", result["code"])
	s.NotEmpty(result["sku"])
	s.Equal("10", result["costPrice"])
	s.Equal("15", result["salePrice"])
	s.Equal("USD", result["currency"])
	s.Equal(float64(2), result["stockQuantity"])
	s.Equal(float64(5), result["stockQuantityAlert"])
}

func (s *InventoryVariantsSuite) TestCreateVariant_ProductNotFound() {
	ctx := context.Background()
	_, ws, token, err := s.accountHelper.CreateTestUser(ctx, "admin@example.com", "Password123!", "Admin", "User", role.RoleAdmin)
	s.NoError(err)
	s.NoError(s.accountHelper.CreateTestSubscription(ctx, ws.ID))
	_, err = s.inventoryHelper.CreateTestBusiness(ctx, ws.ID, "test-biz")
	s.NoError(err)

	payload := map[string]interface{}{
		"productId":          "prod_missing",
		"code":               "RED",
		"costPrice":          "10",
		"salePrice":          "15",
		"stockQuantity":      2,
		"stockQuantityAlert": 5,
	}
	resp, err := s.inventoryHelper.Client.AuthenticatedRequest("POST", "/v1/businesses/test-biz/inventory/variants", payload, token)
	s.NoError(err)
	defer resp.Body.Close()
	s.Equal(http.StatusNotFound, resp.StatusCode)
}

func (s *InventoryVariantsSuite) TestListVariants_Pagination() {
	ctx := context.Background()
	_, ws, token, err := s.accountHelper.CreateTestUser(ctx, "admin@example.com", "Password123!", "Admin", "User", role.RoleAdmin)
	s.NoError(err)
	s.NoError(s.accountHelper.CreateTestSubscription(ctx, ws.ID))
	biz, err := s.inventoryHelper.CreateTestBusiness(ctx, ws.ID, "test-biz")
	s.NoError(err)
	cat, err := s.inventoryHelper.CreateTestCategory(ctx, biz.ID, "Cat", "cat")
	s.NoError(err)
	prod, err := s.inventoryHelper.CreateTestProduct(ctx, biz.ID, cat.ID, "Prod", "")
	s.NoError(err)

	_, err = s.inventoryHelper.CreateTestVariant(ctx, biz.ID, prod.ID, "A", "SKU-A", "USD", decimal.NewFromInt(1), decimal.NewFromInt(2), 1, 0)
	s.NoError(err)
	_, err = s.inventoryHelper.CreateTestVariant(ctx, biz.ID, prod.ID, "B", "SKU-B", "USD", decimal.NewFromInt(1), decimal.NewFromInt(2), 2, 0)
	s.NoError(err)
	_, err = s.inventoryHelper.CreateTestVariant(ctx, biz.ID, prod.ID, "C", "SKU-C", "USD", decimal.NewFromInt(1), decimal.NewFromInt(2), 3, 0)
	s.NoError(err)

	resp, err := s.inventoryHelper.Client.AuthenticatedRequest("GET", "/v1/businesses/test-biz/inventory/variants?page=1&pageSize=2&orderBy=code", nil, token)
	s.NoError(err)
	defer resp.Body.Close()
	s.Equal(http.StatusOK, resp.StatusCode)

	var result map[string]interface{}
	s.NoError(testutils.DecodeJSON(resp, &result))
	s.Equal(float64(3), result["totalCount"])
	items := result["items"].([]interface{})
	s.Len(items, 2)
	s.Equal(true, result["hasMore"])
}

func (s *InventoryVariantsSuite) TestUpdateVariant_UpdatesAndNormalizes() {
	ctx := context.Background()
	_, ws, token, err := s.accountHelper.CreateTestUser(ctx, "admin@example.com", "Password123!", "Admin", "User", role.RoleAdmin)
	s.NoError(err)
	s.NoError(s.accountHelper.CreateTestSubscription(ctx, ws.ID))
	biz, err := s.inventoryHelper.CreateTestBusiness(ctx, ws.ID, "test-biz")
	s.NoError(err)
	cat, err := s.inventoryHelper.CreateTestCategory(ctx, biz.ID, "Cat", "cat")
	s.NoError(err)
	prod, err := s.inventoryHelper.CreateTestProduct(ctx, biz.ID, cat.ID, "Prod", "")
	s.NoError(err)
	v, err := s.inventoryHelper.CreateTestVariant(ctx, biz.ID, prod.ID, "RED", "SKU-RED", "USD", decimal.NewFromInt(10), decimal.NewFromInt(15), 2, 5)
	s.NoError(err)

	newCode := "  BLUE  "
	newSKU := "  sku-new  "
	newCurrency := "egp"
	newCost := decimal.NewFromInt(7)
	newSale := decimal.NewFromInt(9)
	newQty := 11
	newAlert := 3
	payload := map[string]interface{}{
		"code":               &newCode,
		"sku":                &newSKU,
		"currency":           &newCurrency,
		"costPrice":          &newCost,
		"salePrice":          &newSale,
		"stockQuantity":      &newQty,
		"stockQuantityAlert": &newAlert,
	}
	resp, err := s.inventoryHelper.Client.AuthenticatedRequest("PATCH", fmt.Sprintf("/v1/businesses/test-biz/inventory/variants/%s", v.ID), payload, token)
	s.NoError(err)
	defer resp.Body.Close()
	s.Equal(http.StatusOK, resp.StatusCode)

	var result map[string]interface{}
	s.NoError(testutils.DecodeJSON(resp, &result))
	s.Equal("Prod - BLUE", result["name"])
	s.Equal("BLUE", result["code"])
	s.Equal("sku-new", result["sku"])
	s.Equal("EGP", result["currency"])
	s.Equal("7", result["costPrice"])
	s.Equal("9", result["salePrice"])
	s.Equal(float64(11), result["stockQuantity"])
	s.Equal(float64(3), result["stockQuantityAlert"])
}

func (s *InventoryVariantsSuite) TestDeleteVariant_Success() {
	ctx := context.Background()
	_, ws, token, err := s.accountHelper.CreateTestUser(ctx, "admin@example.com", "Password123!", "Admin", "User", role.RoleAdmin)
	s.NoError(err)
	s.NoError(s.accountHelper.CreateTestSubscription(ctx, ws.ID))
	biz, err := s.inventoryHelper.CreateTestBusiness(ctx, ws.ID, "test-biz")
	s.NoError(err)
	cat, err := s.inventoryHelper.CreateTestCategory(ctx, biz.ID, "Cat", "cat")
	s.NoError(err)
	prod, err := s.inventoryHelper.CreateTestProduct(ctx, biz.ID, cat.ID, "Prod", "")
	s.NoError(err)
	v, err := s.inventoryHelper.CreateTestVariant(ctx, biz.ID, prod.ID, "A", "SKU-A", "USD", decimal.NewFromInt(1), decimal.NewFromInt(2), 1, 0)
	s.NoError(err)

	resp, err := s.inventoryHelper.Client.AuthenticatedRequest("DELETE", fmt.Sprintf("/v1/businesses/test-biz/inventory/variants/%s", v.ID), nil, token)
	s.NoError(err)
	defer resp.Body.Close()
	s.Equal(http.StatusNoContent, resp.StatusCode)

	getResp, err := s.inventoryHelper.Client.AuthenticatedRequest("GET", fmt.Sprintf("/v1/businesses/test-biz/inventory/variants/%s", v.ID), nil, token)
	s.NoError(err)
	defer getResp.Body.Close()
	s.Equal(http.StatusNotFound, getResp.StatusCode)
}

func (s *InventoryVariantsSuite) TestManageEndpoints_RequireManagePermission() {
	ctx := context.Background()
	ws, users, err := testutils.CreateWorkspaceWithUsers(ctx, testEnv.Database, "admin@example.com", "Password123!", []struct {
		Email     string
		Password  string
		FirstName string
		LastName  string
		Role      role.Role
	}{
		{Email: "member@example.com", Password: "Password123!", FirstName: "Member", LastName: "User", Role: role.RoleUser},
	})
	s.NoError(err)
	memberToken, err := auth.NewJwtToken(users[1].ID, ws.ID)
	s.NoError(err)
	s.NoError(s.accountHelper.CreateTestSubscription(ctx, ws.ID))
	biz, err := s.inventoryHelper.CreateTestBusiness(ctx, ws.ID, "test-biz")
	s.NoError(err)
	cat, err := s.inventoryHelper.CreateTestCategory(ctx, biz.ID, "Cat", "cat")
	s.NoError(err)
	prod, err := s.inventoryHelper.CreateTestProduct(ctx, biz.ID, cat.ID, "Prod", "")
	s.NoError(err)

	createPayload := map[string]interface{}{
		"productId":          prod.ID,
		"code":               "RED",
		"costPrice":          "10",
		"salePrice":          "15",
		"stockQuantity":      2,
		"stockQuantityAlert": 5,
	}
	resp, err := s.inventoryHelper.Client.AuthenticatedRequest("POST", "/v1/businesses/test-biz/inventory/variants", createPayload, memberToken)
	s.NoError(err)
	resp.Body.Close()
	s.Equal(http.StatusForbidden, resp.StatusCode)
}

func TestInventoryVariantsSuite(t *testing.T) {
	if testServer == nil {
		t.Skip("Test server not initialized")
	}
	suite.Run(t, new(InventoryVariantsSuite))
}
