// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
// file: web/template/components/add_payment_modal.templ

package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AddPaymentModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog id=\"add_payment_modal\" class=\"modal\"><div class=\"modal-box\"><h3 class=\"font-bold text-lg\">Record Payment</h3><form class=\"py-4 space-y-4\"><div class=\"grid grid-cols-1 sm:grid-cols-2 gap-4\"><label class=\"form-control w-full\"><div class=\"label\"><span class=\"label-text\">Date</span></div><input type=\"date\" class=\"input input-bordered w-full\"></label> <label class=\"form-control w-full\"><div class=\"label\"><span class=\"label-text\">Amount</span></div><div class=\"join\"><span class=\"btn join-item no-animation btn-disabled bg-base-200\">$</span> <input type=\"text\" placeholder=\"0.00\" class=\"join-item input input-bordered w-full\"></div></label></div><label class=\"form-control w-full\"><div class=\"label\"><span class=\"label-text\">Payment Method</span></div><select class=\"select select-bordered\"><option>Cash</option> <option>Bank Transfer</option> <option>Credit Card</option> <option>Other</option></select></label> <label class=\"form-control w-full\"><div class=\"label\"><span class=\"label-text\">Reference</span></div><input type=\"text\" placeholder=\"e.g., Transaction ID\" class=\"input input-bordered w-full\"></label> <label class=\"form-control w-full\"><div class=\"label\"><span class=\"label-text\">Notes</span></div><textarea class=\"textarea textarea-bordered h-24\" placeholder=\"Optional notes\"></textarea></label></form><div class=\"modal-action\"><form method=\"dialog\"><button class=\"btn\">Cancel</button> <button class=\"btn btn-primary\">Save Payment</button></form></div></div><form method=\"dialog\" class=\"modal-backdrop\"><button>close</button></form></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
