// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"sticky top-0 z-30 flex h-16 shrink-0 items-center gap-4 border-b border-base-300 bg-base-100/80 backdrop-blur-sm px-4 lg:px-8\"><button x-on:click=\"sidebarOpen = !sidebarOpen\" class=\"btn btn-ghost btn-circle lg:hidden\"><i data-feather=\"menu\" class=\"h-6 w-6\"></i></button><div class=\"relative flex-1\"><a href=\"/\" class=\"text-xl font-bold text-secondary\">Looli Shop</a></div><div class=\"flex items-center gap-2\"><label class=\"swap swap-rotate btn btn-ghost btn-circle\"><input type=\"checkbox\" class=\"theme-controller\" value=\"business\"> <i data-feather=\"sun\" class=\"swap-off h-5 w-5\"></i> <i data-feather=\"moon\" class=\"swap-on h-5 w-5\"></i></label><div class=\"dropdown dropdown-end\"><div tabindex=\"0\" role=\"button\" class=\"btn btn-ghost flex items-center gap-2\"><div class=\"avatar\"><div class=\"w-8 rounded-full\"><img src=\"https://i.pravatar.cc/100?u=john\" alt=\"User Avatar\"></div></div><div class=\"hidden text-left md:block\"><div class=\"font-semibold text-sm\">John Doe</div><div class=\"text-xs text-base-content/60\">Admin</div></div></div><ul tabindex=\"0\" class=\"menu dropdown-content menu-sm z-[1] mt-3 w-52 rounded-box bg-base-100 p-2 shadow\"><li><a href=\"/profile\"><i data-feather=\"user\" class=\"h-4 w-4\"></i> Profile</a></li><li><a href=\"/settings\"><i data-feather=\"settings\" class=\"h-4 w-4\"></i> Settings</a></li><li><a hx-post=\"/logout\"><i data-feather=\"log-out\" class=\"h-4 w-4\"></i> Logout</a></li></ul></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
