/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingVerifyRouteImport } from './routes/onboarding/verify'
import { Route as OnboardingPlanRouteImport } from './routes/onboarding/plan'
import { Route as OnboardingPaymentRouteImport } from './routes/onboarding/payment'
import { Route as OnboardingOauthCallbackRouteImport } from './routes/onboarding/oauth-callback'
import { Route as OnboardingEmailRouteImport } from './routes/onboarding/email'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding/complete'
import { Route as OnboardingBusinessRouteImport } from './routes/onboarding/business'
import { Route as BusinessBusinessDescriptorRouteImport } from './routes/business/$businessDescriptor'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as BusinessBusinessDescriptorIndexRouteImport } from './routes/business/$businessDescriptor/index'
import { Route as AuthOauthCallbackRouteImport } from './routes/auth/oauth/callback'
import { Route as BusinessBusinessDescriptorOrdersIndexRouteImport } from './routes/business/$businessDescriptor/orders/index'
import { Route as BusinessBusinessDescriptorInventoryIndexRouteImport } from './routes/business/$businessDescriptor/inventory/index'
import { Route as BusinessBusinessDescriptorCustomersIndexRouteImport } from './routes/business/$businessDescriptor/customers/index'
import { Route as BusinessBusinessDescriptorAccountingIndexRouteImport } from './routes/business/$businessDescriptor/accounting/index'
import { Route as BusinessBusinessDescriptorCustomersCustomerIdRouteImport } from './routes/business/$businessDescriptor/customers/$customerId'
import { Route as BusinessBusinessDescriptorAccountingCapitalRouteImport } from './routes/business/$businessDescriptor/accounting/capital'
import { Route as BusinessBusinessDescriptorAccountingAssetsRouteImport } from './routes/business/$businessDescriptor/accounting/assets'
import { Route as BusinessBusinessDescriptorAccountingExpensesIndexRouteImport } from './routes/business/$businessDescriptor/accounting/expenses/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingVerifyRoute = OnboardingVerifyRouteImport.update({
  id: '/onboarding/verify',
  path: '/onboarding/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPlanRoute = OnboardingPlanRouteImport.update({
  id: '/onboarding/plan',
  path: '/onboarding/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPaymentRoute = OnboardingPaymentRouteImport.update({
  id: '/onboarding/payment',
  path: '/onboarding/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOauthCallbackRoute = OnboardingOauthCallbackRouteImport.update({
  id: '/onboarding/oauth-callback',
  path: '/onboarding/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingEmailRoute = OnboardingEmailRouteImport.update({
  id: '/onboarding/email',
  path: '/onboarding/email',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/onboarding/complete',
  path: '/onboarding/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBusinessRoute = OnboardingBusinessRouteImport.update({
  id: '/onboarding/business',
  path: '/onboarding/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessBusinessDescriptorRoute =
  BusinessBusinessDescriptorRouteImport.update({
    id: '/business/$businessDescriptor',
    path: '/business/$businessDescriptor',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessBusinessDescriptorIndexRoute =
  BusinessBusinessDescriptorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BusinessBusinessDescriptorRoute,
  } as any)
const AuthOauthCallbackRoute = AuthOauthCallbackRouteImport.update({
  id: '/auth/oauth/callback',
  path: '/auth/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessBusinessDescriptorOrdersIndexRoute =
  BusinessBusinessDescriptorOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => BusinessBusinessDescriptorRoute,
  } as any)
const BusinessBusinessDescriptorInventoryIndexRoute =
  BusinessBusinessDescriptorInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => BusinessBusinessDescriptorRoute,
  } as any)
const BusinessBusinessDescriptorCustomersIndexRoute =
  BusinessBusinessDescriptorCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => BusinessBusinessDescriptorRoute,
  } as any)
const BusinessBusinessDescriptorAccountingIndexRoute =
  BusinessBusinessDescriptorAccountingIndexRouteImport.update({
    id: '/accounting/',
    path: '/accounting/',
    getParentRoute: () => BusinessBusinessDescriptorRoute,
  } as any)
const BusinessBusinessDescriptorCustomersCustomerIdRoute =
  BusinessBusinessDescriptorCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => BusinessBusinessDescriptorRoute,
  } as any)
const BusinessBusinessDescriptorAccountingCapitalRoute =
  BusinessBusinessDescriptorAccountingCapitalRouteImport.update({
    id: '/accounting/capital',
    path: '/accounting/capital',
    getParentRoute: () => BusinessBusinessDescriptorRoute,
  } as any)
const BusinessBusinessDescriptorAccountingAssetsRoute =
  BusinessBusinessDescriptorAccountingAssetsRouteImport.update({
    id: '/accounting/assets',
    path: '/accounting/assets',
    getParentRoute: () => BusinessBusinessDescriptorRoute,
  } as any)
const BusinessBusinessDescriptorAccountingExpensesIndexRoute =
  BusinessBusinessDescriptorAccountingExpensesIndexRouteImport.update({
    id: '/accounting/expenses/',
    path: '/accounting/expenses/',
    getParentRoute: () => BusinessBusinessDescriptorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/business/$businessDescriptor': typeof BusinessBusinessDescriptorRouteWithChildren
  '/onboarding/business': typeof OnboardingBusinessRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/email': typeof OnboardingEmailRoute
  '/onboarding/oauth-callback': typeof OnboardingOauthCallbackRoute
  '/onboarding/payment': typeof OnboardingPaymentRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/auth/oauth/callback': typeof AuthOauthCallbackRoute
  '/business/$businessDescriptor/': typeof BusinessBusinessDescriptorIndexRoute
  '/business/$businessDescriptor/accounting/assets': typeof BusinessBusinessDescriptorAccountingAssetsRoute
  '/business/$businessDescriptor/accounting/capital': typeof BusinessBusinessDescriptorAccountingCapitalRoute
  '/business/$businessDescriptor/customers/$customerId': typeof BusinessBusinessDescriptorCustomersCustomerIdRoute
  '/business/$businessDescriptor/accounting': typeof BusinessBusinessDescriptorAccountingIndexRoute
  '/business/$businessDescriptor/customers': typeof BusinessBusinessDescriptorCustomersIndexRoute
  '/business/$businessDescriptor/inventory': typeof BusinessBusinessDescriptorInventoryIndexRoute
  '/business/$businessDescriptor/orders': typeof BusinessBusinessDescriptorOrdersIndexRoute
  '/business/$businessDescriptor/accounting/expenses': typeof BusinessBusinessDescriptorAccountingExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/onboarding/business': typeof OnboardingBusinessRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/email': typeof OnboardingEmailRoute
  '/onboarding/oauth-callback': typeof OnboardingOauthCallbackRoute
  '/onboarding/payment': typeof OnboardingPaymentRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/auth/oauth/callback': typeof AuthOauthCallbackRoute
  '/business/$businessDescriptor': typeof BusinessBusinessDescriptorIndexRoute
  '/business/$businessDescriptor/accounting/assets': typeof BusinessBusinessDescriptorAccountingAssetsRoute
  '/business/$businessDescriptor/accounting/capital': typeof BusinessBusinessDescriptorAccountingCapitalRoute
  '/business/$businessDescriptor/customers/$customerId': typeof BusinessBusinessDescriptorCustomersCustomerIdRoute
  '/business/$businessDescriptor/accounting': typeof BusinessBusinessDescriptorAccountingIndexRoute
  '/business/$businessDescriptor/customers': typeof BusinessBusinessDescriptorCustomersIndexRoute
  '/business/$businessDescriptor/inventory': typeof BusinessBusinessDescriptorInventoryIndexRoute
  '/business/$businessDescriptor/orders': typeof BusinessBusinessDescriptorOrdersIndexRoute
  '/business/$businessDescriptor/accounting/expenses': typeof BusinessBusinessDescriptorAccountingExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/business/$businessDescriptor': typeof BusinessBusinessDescriptorRouteWithChildren
  '/onboarding/business': typeof OnboardingBusinessRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/email': typeof OnboardingEmailRoute
  '/onboarding/oauth-callback': typeof OnboardingOauthCallbackRoute
  '/onboarding/payment': typeof OnboardingPaymentRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/auth/oauth/callback': typeof AuthOauthCallbackRoute
  '/business/$businessDescriptor/': typeof BusinessBusinessDescriptorIndexRoute
  '/business/$businessDescriptor/accounting/assets': typeof BusinessBusinessDescriptorAccountingAssetsRoute
  '/business/$businessDescriptor/accounting/capital': typeof BusinessBusinessDescriptorAccountingCapitalRoute
  '/business/$businessDescriptor/customers/$customerId': typeof BusinessBusinessDescriptorCustomersCustomerIdRoute
  '/business/$businessDescriptor/accounting/': typeof BusinessBusinessDescriptorAccountingIndexRoute
  '/business/$businessDescriptor/customers/': typeof BusinessBusinessDescriptorCustomersIndexRoute
  '/business/$businessDescriptor/inventory/': typeof BusinessBusinessDescriptorInventoryIndexRoute
  '/business/$businessDescriptor/orders/': typeof BusinessBusinessDescriptorOrdersIndexRoute
  '/business/$businessDescriptor/accounting/expenses/': typeof BusinessBusinessDescriptorAccountingExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/business/$businessDescriptor'
    | '/onboarding/business'
    | '/onboarding/complete'
    | '/onboarding/email'
    | '/onboarding/oauth-callback'
    | '/onboarding/payment'
    | '/onboarding/plan'
    | '/onboarding/verify'
    | '/onboarding'
    | '/auth/oauth/callback'
    | '/business/$businessDescriptor/'
    | '/business/$businessDescriptor/accounting/assets'
    | '/business/$businessDescriptor/accounting/capital'
    | '/business/$businessDescriptor/customers/$customerId'
    | '/business/$businessDescriptor/accounting'
    | '/business/$businessDescriptor/customers'
    | '/business/$businessDescriptor/inventory'
    | '/business/$businessDescriptor/orders'
    | '/business/$businessDescriptor/accounting/expenses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/onboarding/business'
    | '/onboarding/complete'
    | '/onboarding/email'
    | '/onboarding/oauth-callback'
    | '/onboarding/payment'
    | '/onboarding/plan'
    | '/onboarding/verify'
    | '/onboarding'
    | '/auth/oauth/callback'
    | '/business/$businessDescriptor'
    | '/business/$businessDescriptor/accounting/assets'
    | '/business/$businessDescriptor/accounting/capital'
    | '/business/$businessDescriptor/customers/$customerId'
    | '/business/$businessDescriptor/accounting'
    | '/business/$businessDescriptor/customers'
    | '/business/$businessDescriptor/inventory'
    | '/business/$businessDescriptor/orders'
    | '/business/$businessDescriptor/accounting/expenses'
  id:
    | '__root__'
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/business/$businessDescriptor'
    | '/onboarding/business'
    | '/onboarding/complete'
    | '/onboarding/email'
    | '/onboarding/oauth-callback'
    | '/onboarding/payment'
    | '/onboarding/plan'
    | '/onboarding/verify'
    | '/onboarding/'
    | '/auth/oauth/callback'
    | '/business/$businessDescriptor/'
    | '/business/$businessDescriptor/accounting/assets'
    | '/business/$businessDescriptor/accounting/capital'
    | '/business/$businessDescriptor/customers/$customerId'
    | '/business/$businessDescriptor/accounting/'
    | '/business/$businessDescriptor/customers/'
    | '/business/$businessDescriptor/inventory/'
    | '/business/$businessDescriptor/orders/'
    | '/business/$businessDescriptor/accounting/expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  BusinessBusinessDescriptorRoute: typeof BusinessBusinessDescriptorRouteWithChildren
  OnboardingBusinessRoute: typeof OnboardingBusinessRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingEmailRoute: typeof OnboardingEmailRoute
  OnboardingOauthCallbackRoute: typeof OnboardingOauthCallbackRoute
  OnboardingPaymentRoute: typeof OnboardingPaymentRoute
  OnboardingPlanRoute: typeof OnboardingPlanRoute
  OnboardingVerifyRoute: typeof OnboardingVerifyRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  AuthOauthCallbackRoute: typeof AuthOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/verify': {
      id: '/onboarding/verify'
      path: '/onboarding/verify'
      fullPath: '/onboarding/verify'
      preLoaderRoute: typeof OnboardingVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/plan': {
      id: '/onboarding/plan'
      path: '/onboarding/plan'
      fullPath: '/onboarding/plan'
      preLoaderRoute: typeof OnboardingPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/payment': {
      id: '/onboarding/payment'
      path: '/onboarding/payment'
      fullPath: '/onboarding/payment'
      preLoaderRoute: typeof OnboardingPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/oauth-callback': {
      id: '/onboarding/oauth-callback'
      path: '/onboarding/oauth-callback'
      fullPath: '/onboarding/oauth-callback'
      preLoaderRoute: typeof OnboardingOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/email': {
      id: '/onboarding/email'
      path: '/onboarding/email'
      fullPath: '/onboarding/email'
      preLoaderRoute: typeof OnboardingEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/onboarding/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/business': {
      id: '/onboarding/business'
      path: '/onboarding/business'
      fullPath: '/onboarding/business'
      preLoaderRoute: typeof OnboardingBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$businessDescriptor': {
      id: '/business/$businessDescriptor'
      path: '/business/$businessDescriptor'
      fullPath: '/business/$businessDescriptor'
      preLoaderRoute: typeof BusinessBusinessDescriptorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$businessDescriptor/': {
      id: '/business/$businessDescriptor/'
      path: '/'
      fullPath: '/business/$businessDescriptor/'
      preLoaderRoute: typeof BusinessBusinessDescriptorIndexRouteImport
      parentRoute: typeof BusinessBusinessDescriptorRoute
    }
    '/auth/oauth/callback': {
      id: '/auth/oauth/callback'
      path: '/auth/oauth/callback'
      fullPath: '/auth/oauth/callback'
      preLoaderRoute: typeof AuthOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$businessDescriptor/orders/': {
      id: '/business/$businessDescriptor/orders/'
      path: '/orders'
      fullPath: '/business/$businessDescriptor/orders'
      preLoaderRoute: typeof BusinessBusinessDescriptorOrdersIndexRouteImport
      parentRoute: typeof BusinessBusinessDescriptorRoute
    }
    '/business/$businessDescriptor/inventory/': {
      id: '/business/$businessDescriptor/inventory/'
      path: '/inventory'
      fullPath: '/business/$businessDescriptor/inventory'
      preLoaderRoute: typeof BusinessBusinessDescriptorInventoryIndexRouteImport
      parentRoute: typeof BusinessBusinessDescriptorRoute
    }
    '/business/$businessDescriptor/customers/': {
      id: '/business/$businessDescriptor/customers/'
      path: '/customers'
      fullPath: '/business/$businessDescriptor/customers'
      preLoaderRoute: typeof BusinessBusinessDescriptorCustomersIndexRouteImport
      parentRoute: typeof BusinessBusinessDescriptorRoute
    }
    '/business/$businessDescriptor/accounting/': {
      id: '/business/$businessDescriptor/accounting/'
      path: '/accounting'
      fullPath: '/business/$businessDescriptor/accounting'
      preLoaderRoute: typeof BusinessBusinessDescriptorAccountingIndexRouteImport
      parentRoute: typeof BusinessBusinessDescriptorRoute
    }
    '/business/$businessDescriptor/customers/$customerId': {
      id: '/business/$businessDescriptor/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/business/$businessDescriptor/customers/$customerId'
      preLoaderRoute: typeof BusinessBusinessDescriptorCustomersCustomerIdRouteImport
      parentRoute: typeof BusinessBusinessDescriptorRoute
    }
    '/business/$businessDescriptor/accounting/capital': {
      id: '/business/$businessDescriptor/accounting/capital'
      path: '/accounting/capital'
      fullPath: '/business/$businessDescriptor/accounting/capital'
      preLoaderRoute: typeof BusinessBusinessDescriptorAccountingCapitalRouteImport
      parentRoute: typeof BusinessBusinessDescriptorRoute
    }
    '/business/$businessDescriptor/accounting/assets': {
      id: '/business/$businessDescriptor/accounting/assets'
      path: '/accounting/assets'
      fullPath: '/business/$businessDescriptor/accounting/assets'
      preLoaderRoute: typeof BusinessBusinessDescriptorAccountingAssetsRouteImport
      parentRoute: typeof BusinessBusinessDescriptorRoute
    }
    '/business/$businessDescriptor/accounting/expenses/': {
      id: '/business/$businessDescriptor/accounting/expenses/'
      path: '/accounting/expenses'
      fullPath: '/business/$businessDescriptor/accounting/expenses'
      preLoaderRoute: typeof BusinessBusinessDescriptorAccountingExpensesIndexRouteImport
      parentRoute: typeof BusinessBusinessDescriptorRoute
    }
  }
}

interface BusinessBusinessDescriptorRouteChildren {
  BusinessBusinessDescriptorIndexRoute: typeof BusinessBusinessDescriptorIndexRoute
  BusinessBusinessDescriptorAccountingAssetsRoute: typeof BusinessBusinessDescriptorAccountingAssetsRoute
  BusinessBusinessDescriptorAccountingCapitalRoute: typeof BusinessBusinessDescriptorAccountingCapitalRoute
  BusinessBusinessDescriptorCustomersCustomerIdRoute: typeof BusinessBusinessDescriptorCustomersCustomerIdRoute
  BusinessBusinessDescriptorAccountingIndexRoute: typeof BusinessBusinessDescriptorAccountingIndexRoute
  BusinessBusinessDescriptorCustomersIndexRoute: typeof BusinessBusinessDescriptorCustomersIndexRoute
  BusinessBusinessDescriptorInventoryIndexRoute: typeof BusinessBusinessDescriptorInventoryIndexRoute
  BusinessBusinessDescriptorOrdersIndexRoute: typeof BusinessBusinessDescriptorOrdersIndexRoute
  BusinessBusinessDescriptorAccountingExpensesIndexRoute: typeof BusinessBusinessDescriptorAccountingExpensesIndexRoute
}

const BusinessBusinessDescriptorRouteChildren: BusinessBusinessDescriptorRouteChildren =
  {
    BusinessBusinessDescriptorIndexRoute: BusinessBusinessDescriptorIndexRoute,
    BusinessBusinessDescriptorAccountingAssetsRoute:
      BusinessBusinessDescriptorAccountingAssetsRoute,
    BusinessBusinessDescriptorAccountingCapitalRoute:
      BusinessBusinessDescriptorAccountingCapitalRoute,
    BusinessBusinessDescriptorCustomersCustomerIdRoute:
      BusinessBusinessDescriptorCustomersCustomerIdRoute,
    BusinessBusinessDescriptorAccountingIndexRoute:
      BusinessBusinessDescriptorAccountingIndexRoute,
    BusinessBusinessDescriptorCustomersIndexRoute:
      BusinessBusinessDescriptorCustomersIndexRoute,
    BusinessBusinessDescriptorInventoryIndexRoute:
      BusinessBusinessDescriptorInventoryIndexRoute,
    BusinessBusinessDescriptorOrdersIndexRoute:
      BusinessBusinessDescriptorOrdersIndexRoute,
    BusinessBusinessDescriptorAccountingExpensesIndexRoute:
      BusinessBusinessDescriptorAccountingExpensesIndexRoute,
  }

const BusinessBusinessDescriptorRouteWithChildren =
  BusinessBusinessDescriptorRoute._addFileChildren(
    BusinessBusinessDescriptorRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  BusinessBusinessDescriptorRoute: BusinessBusinessDescriptorRouteWithChildren,
  OnboardingBusinessRoute: OnboardingBusinessRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingEmailRoute: OnboardingEmailRoute,
  OnboardingOauthCallbackRoute: OnboardingOauthCallbackRoute,
  OnboardingPaymentRoute: OnboardingPaymentRoute,
  OnboardingPlanRoute: OnboardingPlanRoute,
  OnboardingVerifyRoute: OnboardingVerifyRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  AuthOauthCallbackRoute: AuthOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
