// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/abdelrahman146/kyora/internal/web/views/layouts"

type Stat struct {
	Label string
	Value string
	Delta string // e.g. +12% vs last 7d
}

func Dashboard(stats []Stat) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"prose max-w-none\"><h1 class=\"text-2xl font-bold mb-4\">Dashboard Overview</h1><p>Welcome back! Here's a quick look at your business.</p><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mt-6\"><div class=\"card bg-base-100 shadow-lg\"><div class=\"card-body\"><h2 class=\"card-title\">Revenue (30d)</h2><p class=\"text-3xl font-bold\">$12,450</p><p class=\"text-success\">+12% from last month</p></div></div><div class=\"card bg-base-100 shadow-lg\"><div class=\"card-body\"><h2 class=\"card-title\">New Orders (30d)</h2><p class=\"text-3xl font-bold\">82</p><p class=\"text-success\">+5 from last month</p></div></div><div class=\"card bg-base-100 shadow-lg\"><div class=\"card-body\"><h2 class=\"card-title\">Avg. Order Value</h2><p class=\"text-3xl font-bold\">$151.83</p><p class=\"text-error\">-3% from last month</p></div></div><div class=\"card bg-base-100 shadow-lg\"><div class=\"card-body\"><h2 class=\"card-title\">New Customers</h2><p class=\"text-3xl font-bold\">35</p><p class=\"text-success\">+20% from last month</p></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.AppLayout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
