// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
// file: web/template/pages/report_customers.templ

package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/abdelrahman146/kyora/internal/web/views/components"
	"github.com/abdelrahman146/kyora/internal/web/views/layouts"
)

func CustomerMixChart() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_CustomerMixChart_eaf3`,
		Function: `function __templ_CustomerMixChart_eaf3(){document.addEventListener('DOMContentLoaded', () => {
            const colors = window.kyora.colors();

            // Customer Mix Chart
            window.kyora.renderChart('customerMixChart', {
                  type: 'bar',
                  data: {
                        labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
                        datasets: [{
                              label: 'New Customers',
                              data: [20, 25, 30, 28, 35, 32],
                              backgroundColor: colors.primary,
                        }, {
                              label: 'Returning Customers',
                              data: [15, 18, 22, 25, 30, 58],
                              backgroundColor: colors.secondary,
                        }]
                  },
                  options: { scales: { x: { stacked: true }, y: { stacked: true } } }
            });
      });
}`,
		Call:       templ.SafeScript(`__templ_CustomerMixChart_eaf3`),
		CallInline: templ.SafeScriptInline(`__templ_CustomerMixChart_eaf3`),
	}
}

func CustomersReport() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-6\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.PageHeader(EmptyQuickActions()).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-5\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.StatCard("Total Customers", "452", "32", "increase", "This Period", "users").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.StatCard("New Customers", "32", "18.5%", "increase", "vs. Last Period", "user-plus").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.StatCard("Returning Customers", "58", "5.1%", "increase", "This Period", "user-check").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.StatCard("Lifetime Value (LTV)", "$128.50", "4.2%", "increase", "Avg. per customer", "dollar-sign").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.StatCard("Avg. Orders/Customer", "2.3", "0.1", "increase", "Avg. orders per customer", "repeat").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"grid grid-cols-1 lg:grid-cols-2 gap-6\"><div class=\"card bg-base-100 shadow\"><div class=\"card-body\"><h2 class=\"card-title\">New vs. Returning Customers</h2><p class=\"text-sm text-base-content/60\">This chart shows the mix of new and repeat customers each month. A healthy business grows both, indicating good acquisition and retention.</p><div class=\"h-96 mt-4\"><canvas id=\"customerMixChart\"></canvas></div></div></div><div class=\"card bg-base-100 shadow\"><div class=\"card-body\"><h2 class=\"card-title\">Top Customers by Spend</h2><p class=\"text-sm text-base-content/60\">Your most valuable customers. Consider creating special offers or loyalty programs for this group to encourage repeat business.</p><div class=\"overflow-x-auto mt-4\"><table class=\"table\"><thead><tr><th>Customer</th><th>Orders</th><th>Total Spend</th></tr></thead> <tbody><tr><td>Anthony J. Lew</td><td>68</td><td>$1,241</td></tr><tr><td>James J. Herron</td><td>54</td><td>$1,080</td></tr><tr><td>Olivia Smith</td><td>25</td><td>$894</td></tr></tbody></table></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = CustomerMixChart().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.AppLayout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
