// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
// file: web/template/pages/report_pnl.templ

package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/abdelrahman146/kyora/internal/web/views/components"
	"github.com/abdelrahman146/kyora/internal/web/views/layouts"
)

func ProfitabilityChart() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_ProfitabilityChart_333c`,
		Function: `function __templ_ProfitabilityChart_333c(){document.addEventListener('DOMContentLoaded', () => {
            const colors = window.kyora.colors();

            // Profitability Chart
            window.kyora.renderChart('profitabilityChart', {
                  type: 'bar',
                  data: {
                        labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
                        datasets: [{
                              label: 'Revenue',
                              data: [1500, 2200, 1800, 2500, 3200, 4100],
                              backgroundColor: colors.neutral,
                        },{
                              label: 'Gross Profit',
                              data: [1000, 1600, 1250, 1800, 2400, 3150],
                              backgroundColor: colors.secondary,
                        },{
                              label: 'Net Profit',
                              data: [200, 750, 350, 850, 1300, 1950],
                              backgroundColor: colors.primary,
                        }]
                  }
            });
      });
}`,
		Call:       templ.SafeScript(`__templ_ProfitabilityChart_333c`),
		CallInline: templ.SafeScriptInline(`__templ_ProfitabilityChart_333c`),
	}
}

func ReportPNL() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-6\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.PageHeader(EmptyQuickActions()).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.StatCard("Gross Profit", "$7,630", "18.1%", "increase", "Revenue - COGS", "trending-up").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.StatCard("Net Profit", "$4,960", "22.3%", "increase", "Gross Profit - Opex", "award").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.StatCard("Gross Margin", "61.3%", "1.2%", "increase", "Profit / Revenue", "pie-chart").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.StatCard("Net Margin", "39.8%", "3.5%", "increase", "Net Profit / Revenue", "pie-chart").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"grid grid-cols-1 lg:grid-cols-5 gap-6\"><div class=\"card bg-base-100 shadow lg:col-span-3\"><div class=\"card-body\"><h2 class=\"card-title\">Profitability Over Time</h2><p class=\"text-sm text-base-content/60\">This chart breaks down your revenue into gross and net profit, showing the core health of your business month by month.</p><div class=\"h-96 mt-4\"><canvas id=\"profitabilityChart\"></canvas></div></div></div><div class=\"card bg-base-100 shadow lg:col-span-2\"><div class=\"card-body\"><h2 class=\"card-title\">P&L Statement (Cash Basis)</h2><p class=\"text-sm text-base-content/60\">A summary of your finances for the selected period. This is the simplest way to see if you're making or losing money.</p><div class=\"overflow-x-auto mt-4\"><table class=\"table\"><tbody><tr><td>Net Revenue</td><td class=\"text-right font-mono\">$12,450</td></tr><tr><td>Cost of Goods Sold (COGS)</td><td class=\"text-right font-mono\">-$4,820</td></tr><tr class=\"font-bold bg-base-200\"><td>Gross Profit</td><td class=\"text-right font-mono\">$7,630</td></tr><tr><td>Operating Expenses (Opex)</td><td class=\"text-right font-mono\">-$2,670</td></tr><tr class=\"font-bold text-lg bg-base-200 text-success\"><td>Net Profit</td><td class=\"text-right font-mono\">$4,960</td></tr></tbody></table></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.AppLayout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
