// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
// file: web/template/pages/report_expenses.templ

package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/abdelrahman146/kyora/internal/web/views/components"
	"github.com/abdelrahman146/kyora/internal/web/views/layouts"
)

func ExpenseBreakdownChart() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_ExpenseBreakdownChart_0ab5`,
		Function: `function __templ_ExpenseBreakdownChart_0ab5(){document.addEventListener('DOMContentLoaded', () => {
            const colors = window.kyora.colors();

            // Expense Breakdown Chart
            window.kyora.renderChart('expenseBreakdownChart', {
                  type: 'pie',
                  data: {
                        labels: ['COGS: Materials', 'COGS: Packaging', 'Opex: Marketing', 'Opex: Software', 'Opex: Admin'],
                        datasets: [{
                              data: [1800, 350, 1200, 870, 600],
                              backgroundColor: [colors.primary, ` + "`" + `rgba(${colors.primary.slice(4,-1)}, 0.7)` + "`" + `, colors.secondary, ` + "`" + `rgba(${colors.secondary.slice(4,-1)}, 0.7)` + "`" + `, colors.accent]
                        }]
                  },
                  options: { scales: { x: { display: false }, y: { display: false } } }
            });
      });
}`,
		Call:       templ.SafeScript(`__templ_ExpenseBreakdownChart_0ab5`),
		CallInline: templ.SafeScriptInline(`__templ_ExpenseBreakdownChart_0ab5`),
	}
}

func COGSvsOpexChart() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_COGSvsOpexChart_deae`,
		Function: `function __templ_COGSvsOpexChart_deae(){document.addEventListener('DOMContentLoaded', () => {
            const colors = window.kyora.colors();

            // COGS vs Opex Chart
            window.kyora.renderChart('cogsVsOpexChart', {
                  type: 'bar',
                  data: {
                        labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
                        datasets: [{
                              label: 'COGS',
                              data: [500, 600, 550, 700, 800, 950],
                              backgroundColor: colors.primary,
                        },{
                              label: 'Opex',
                              data: [800, 850, 900, 950, 1100, 1200],
                              backgroundColor: colors.secondary,
                        }]
                  },
                  options: { scales: { x: { stacked: true }, y: { stacked: true } } }
            });
      });
}`,
		Call:       templ.SafeScript(`__templ_COGSvsOpexChart_deae`),
		CallInline: templ.SafeScriptInline(`__templ_COGSvsOpexChart_deae`),
	}
}

func ExpensesReport() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-6\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.PageHeader(EmptyQuickActions()).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.StatCard("Total Expenses", "$4,820", "5.1%", "increase", "This Period", "trending-down").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.StatCard("COGS", "$2,150", "3.2%", "increase", "Cost of Goods Sold", "package").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.StatCard("Opex", "$2,670", "7.8%", "increase", "Operating Expenses", "briefcase").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.StatCard("Top Category", "Marketing", "$1,200", "increase", "This Period", "bar-chart").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"grid grid-cols-1 lg:grid-cols-2 gap-6\"><div class=\"card bg-base-100 shadow\"><div class=\"card-body\"><h2 class=\"card-title\">Expense Breakdown</h2><p class=\"text-sm text-base-content/60\">This shows where your money is going. High COGS might impact margins, while high Opex could mean high operational costs. Keep an eye on both.</p><div class=\"h-96 mt-4 flex items-center justify-center\"><canvas id=\"expenseBreakdownChart\"></canvas></div></div></div><div class=\"card bg-base-100 shadow\"><div class=\"card-body\"><h2 class=\"card-title\">COGS vs. Opex Over Time</h2><p class=\"text-sm text-base-content/60\">Tracks your direct costs (COGS) vs. your operational costs (Opex). This helps you see if costs are scaling appropriately with your sales.</p><div class=\"h-96 mt-4\"><canvas id=\"cogsVsOpexChart\"></canvas></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ExpenseBreakdownChart().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = COGSvsOpexChart().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.AppLayout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
